docs/configuration.md

Updated documentation to use secure port to scrape kubelet summary metrics.

Updated document to use secure port to scrape summary metrics

---

plugins/sources/stats/provider.go

Temporal solution for https://github.com/rcrowley/go-metrics/issues/252
> Zero values are reported when RegisterDebugGCStats and RegisterRuntimeMemStats are called more than once

Solved reload bug on InternalStats

---

deploy/openshift/openshift-operator/deploy/crds/wavefront-collector-operator_v1beta1_cr.yaml
docs/openshift-operator.md

Quick way to experiment with the collector in Openshift is to use direct ingestion as setting up proxy needs pvc creation so defaulting to direct ingestion.

Updated openshift operator configs

---

deploy/examples/conf.example.yaml

Minor changes to blacklist only `kube.pod.container.resource.limits.*` metrics, not `kube.pod.container.resource.requests.*`

Blacklisting only 'kube.pod.container.resource.limits.*' metrics, not requests.*

---

deploy/examples/conf.example.yaml
deploy/kubernetes/4-collector-config.yaml

clean up example auto-discovery configs, and added coredns configuration.
Also addresses MONIT-16705 adding `annotation_kubectl_kubernetes_io_last_applied_configuration` to the tag exclude

clean examples and add coredns

---

Makefile
cmd/wavefront-collector/main.go
internal/discovery/configs.go
plugins/discovery/config.go
plugins/discovery/config_test.go
plugins/discovery/manager.go

Added support for dynamically sourcing discovery rules:
- Allows users to add/update/delete specific workload related discovery rules as separate config maps with certain annotations (within the same namespace as collector for now)
- Enabled via `discovery.enable_runtime_plugins` property (defaults to false at this time)
- Added a separate config handler to listen for these changes. And the discovery manager sources these changes every X minutes (configured via `discovery.DiscoveryInterval` which defaults to 5 minutes)
Together with the annotations based discovery we already have, this allows the main config file to be owned/locked down by admins while allowing users to enable monitoring of apps/workloads they own by deploying discovery rules relevant to just that piece.

Support dynamically sourcing discovery rules

---

Makefile
internal/discovery/endpoint.go
internal/filter/glob.go
internal/metrics/types.go
plugins/sinks/manager.go
plugins/sinks/wavefront/wavefront.go
plugins/sources/manager.go
plugins/sources/prometheus/prometheus.go
plugins/sources/prometheus/prometheus_test.go
plugins/sources/summary/wavefront_converter.go

Collector instance was OOM killed when collecting data from very large prometheus endpoints (exposing ~1M points). A fair chunk of heap is allocated by the prometheus text parser when parsing the response body. That has not been optimized as part of this PR.
Optimizations addressed in this PR:
- Changed to not read entire response body into memory (ioutil.ReadAll over allocates memory). Instead use a pre-allocated buffer (this allocates memory equal to the response content length).
- Avoid tag creation when only metric name based filtering is enabled at the prometheus source level
- Pass through prometheus labels to sink when possible (avoiding creating additional maps altogether)
Also modified high volume trace/debug level logging to check whether level is enabled before logging.
Memory …

memory optimizations

---

internal/discovery/types.go
plugins/discovery/discoverer.go
plugins/discovery/filter.go
plugins/discovery/filter_test.go
plugins/discovery/pod.go
plugins/discovery/service.go
plugins/processors/rate_calculator.go

- Fixed a memory leak in the rate calculator (we were holding onto deleted pods/containers forever). We now prune the internal cache every 5 minutes.
- Tweaked the discovery mechanism to kick off discovery only if pods/services are ready (IPs assigned and running). This reduces allocations & cpu usage in high churn environments.

Memory improvements

---

README.md
deploy/examples/conf.example.yaml
deploy/kubernetes/4-collector-config.yaml
docs/configuration.md
docs/filtering.md
internal/configuration/config.go
internal/configuration/parser_test.go
internal/discovery/parser_test.go
internal/filter/config.go
internal/filter/glob.go
internal/filter/glob_test.go
internal/filter/util.go
internal/filter/util_test.go
internal/options/adapter.go
plugins/discovery/config_test.go
plugins/events/filter.go
plugins/events/filter_test.go
plugins/sources/prometheus/prometheus_test.go
plugins/sources/summary/converter_test.go
plugins/sources/systemd/filter.go
plugins/sources/systemd/filter_test.go
plugins/sources/systemd/systemd.go

- renames filter vars to use allow/deny-list terminlogy
- previous terms are deprecated for now (retained for backwards compat). We will remove that at a later stage.

rename whitelist/blacklist to allow/deny-list

---

cmd/wavefront-collector/main.go
internal/configuration/config.go
plugins/sources/prometheus/lookahead_reader.go
plugins/sources/prometheus/lookahead_reader_test.go
plugins/sources/prometheus/metric_reader.go
plugins/sources/prometheus/metric_reader_test.go
plugins/sources/prometheus/prometheus.go

MONIT-20817
Breaks the incoming prometheus scrape into groups of metrics to process individually. Shows 40% improvement on memory demands.

Chunked prom parsing to lower memory usage

---

docs/configuration.md
docs/discovery.md
internal/discovery/configs.go
internal/discovery/endpoint.go
internal/discovery/types.go
internal/discovery/utils/encoding.go
internal/util/dummies.go
plugins/discovery/discoverer.go
plugins/discovery/endpoint_creator.go
plugins/discovery/endpoint_creator_test.go

- Move discovery of endpoints from resources to new endpointCreator
- Add unit tests for new endpointCreator
- Add documentation about new config value disable_annotation_discovery
[MONIT-21378](https://wavefront.atlassian.net/browse/MONIT-21378)

Add flag to disable annotation discovery

---

Makefile
hack/kustomize/base/4-collector-config.yaml
hack/kustomize/deploy.sh
hack/kustomize/test.sh

- Redeploy collector in deploy script without flush once to make validating with our dashboard a little quicker
- Added make target for running our validation test we added
- Updated test config to be inline with our default config
- Apply prometheus example as part of deploy script to make first run easier

Updates for local workflows

---

plugins/sources/prometheus/prometheus.go

Remove the group by group debug message in the prometheus debug logging

Reduce debug log clutter

---

.dockerignore
.gitignore

* the change that fixed this was adding a .dockerignore file to exclude
files that were unnecessarily busting the docker cache
* does not affect the test-proxy-container build (need to convert to
mulit-stage build first)
* shaves off 20 to 60 seconds of build time when all things are cached
Signed-off-by: John Cornish <jcornish@vmware.com>

use docker build cache effectively for the container build to improve full-loop performance

---

docs/discovery.md

This reverts commit 164d776f07bff3949c65abb9dbd93eeba67852f2.

Revert "Don't use the prometheus.io/scrape annotation by default (#101)"

---

hack/kustomize/base/collector.template.yaml
hack/kustomize/files/metrics.jsonl
hack/kustomize/test.sh

Minor change outside of adding cAdvisor stuff: my curl returns '000' as an HTTP status code when it cannot connect to the server. Previously, we were using `-eq 0` to test if the test proxy server was up or not. Unfortunately, this doesn't seem to work on my newly imaged machine. So I'm using `-lt 200` instead which appears to do the right thing.

Add cadvisor to integration test

---

ci.Jenkinsfile

To reduce the consecutive failure messages on slack team channel, using the [`regression` condition](https://www.jenkins.io/doc/book/pipeline/syntax/#post-conditions) to only alert on first failure in a PR.

Notify only on regression (good to bad), not on consecutive failures

---

internal/metrics/metrics.go
internal/metrics/types.go
plugins/manager/manager_test.go
plugins/processors/cluster_aggregator_test.go
plugins/processors/namespace_aggregator_test.go
plugins/processors/node_aggregator_test.go
plugins/processors/node_autoscaling_enricher.go
plugins/processors/pod_aggregator_test.go
plugins/processors/pod_based_enricher.go
plugins/processors/pod_based_enricher_test.go
plugins/processors/rate_calculator.go
plugins/processors/rate_calculator_test.go
plugins/sources/summary/converter_test.go
plugins/sources/summary/summary.go

Code search in Goland reveals that this field is only ever written to and never read.

Remove MetricType from MetricValue since it's unused

---

Makefile
cmd/test-proxy/diff.go
cmd/test-proxy/main.go
deploy/kubernetes/4-collector-config.yaml
docs/discovery.md
hack/test/.gitignore
hack/test/base/collector.template.yaml
hack/test/base/proxy.template.yaml
hack/test/base/test-proxy.yaml
hack/test/deploy/deploy-targets.sh
hack/test/deploy/exclude-prom-example.yaml
hack/test/files/metrics.jsonl
hack/test/test-integration.sh
internal/configuration/parser_test.go
internal/discovery/configs.go
make/k8s-envs/kind.mk
plugins/discovery/config.go
plugins/discovery/discoverer.go
plugins/discovery/endpoint_creator.go
plugins/discovery/endpoint_creator_test.go
plugins/discovery/filter.go
plugins/discovery/filter_test.go

Other changes
* Stop building the test-proxy on every integration test since we're not actually using the locally built version
* test-proxy
+ allow metric patterns posted to `/metrics/diff` to contain `~` in front of the whole metric to signal that it should be excluded
+ Add an Unwanted field to report metrics that should have been excluded but were not
* integration-test
+ fail if there are any Unwanted metrics
+ add excluded metric that tests new `annotation_excludes` config

Add annotation_excludes field to discovery config

---

Makefile

using go get to install executables is deprecated in go 1.17. https://go.dev/doc/go-get-install-deprecation#:~:text=Starting%20in%20Go%201.17%2C%20installing,the%20%2Dd%20flag%20were%20enabled.

Update deprecated 'go get' to 'go install'

---

cmd/wavefront-collector/main.go
hack/test/files/metrics.jsonl
internal/metrics/resource_key.go
internal/metrics/set.go
internal/metrics/types.go
plugins/processors/cluster_aggregator.go
plugins/processors/cluster_aggregator_test.go
plugins/processors/namespace_aggregator.go
plugins/processors/namespace_aggregator_test.go
plugins/processors/node_aggregator.go
plugins/processors/node_aggregator_test.go
plugins/processors/sum_count_aggregator.go
plugins/processors/sum_count_aggregator_test.go
plugins/sources/summary/converter_utils.go

This comes with a refactor to extract common aggregation logic to `SumCountAggregator`. Node, namespace, and cluster now use it instead of implementing their own aggregators.

Exclude completed pods from node, namespace, and cluster aggregates
