wavefrontHQ/wavefront-collector-for-kubernetes

docs/openshift.md
Added supported version section.
=> Minor doc changes

Makefile, cmd/wavefront-collector/main.go, internal/flags/utils.go, plugins/sinks/wavefront/driver_test.go, plugins/sinks/wavefront/wavefront.go, plugins/sources/summary/converter_test.go, plugins/sources/summary/converter_utils.go, plugins/sources/summary/summary.go, plugins/sources/summary/wavefront_converter.go
=> refactor sink and summary/stats code

internal/util/tags.go, plugins/sources/prometheus/prometheus.go, plugins/sources/prometheus/prometheus_test.go
```
benchmark                  old ns/op     new ns/op     delta
BenchmarkBuildTags1-8      172           128           -25.58%
BenchmarkBuildTags2-8      191           219           +14.66%
BenchmarkBuildTags4-8      239           354           +48.12%
BenchmarkBuildTags8-8      341           622           +82.40%
BenchmarkBuildTags16-8     1852          1203          -35.04%
benchmark                  old allocs     new allocs     delta
BenchmarkBuildTags1-8      2              1              -50.00%
BenchmarkBuildTags2-8      2              1              -50.00%
BenchmarkBuildTags4-8      2              1              -50.00%
BenchmarkBuildTags8-8      2              1              -50.00%
BenchmarkBuildTags16-8     4              1              -75.00%
benchmark                  old …
```
=> prometheus collection memory improvements

deploy/pks/5-collector-deployment.yaml
update kubelet port expose for PKS to 10250
=> update kubelet port expose for PKS

deploy/openshift/openshift-operator/deploy/operator.yaml
=> Updated operator version

deploy/examples/conf.example.yaml
Updating default configs to filter labels `label.controller.revision.hash`, `label.pod.temple.hash` and `label.pod.temple.generation` in conf.example.yaml file.
- Jira ticket: https://wavefront.atlassian.net/browse/INT-487
=> INT-487 Updating tagExclude for proxy sink

plugins/sources/prometheus/prometheus.go, plugins/sources/prometheus/prometheus_test.go
solution for: https://wavefront.atlassian.net/browse/MONIT-16235
=> Tag filtering for prometheus

Makefile, deploy/docker/Dockerfile-rhel
Added make target to build collector using rhel ubi base image.
=> Added support to run collector in Red Hat UBI

docs/openshift-operator.md
Updated steps to deploy WF proxy and storage without using webconsole and added steps to uninstall operator and its components from Openshift 3.11 cluster.
=> Updated WF proxy deployment steps and operator uninstall steps.

deploy/examples/openshift-collector-configmap.yaml
Adding openshift collector configmap example.
=> Adding openshift collector configmap example.

deploy/docker/Dockerfile-rhel, deploy/examples/openshift-collector-configmap.yaml, deploy/examples/openshift-config.yaml, docs/openshift-operator.md
Updated collector version, proxy service name in openshift config files and minor doc update
=> Updated version in openshift config files

deploy/openshift/1-wavefront-proxy.yaml
Updated proxy version to use 5.7
=> Pinned wavefront proxy to 5.7

README.md, cmd/wavefront-collector/main.go, plugins/processors/pod_based_enricher.go, plugins/processors/pod_based_enricher_test.go
If our observation interval jumped over a termination, report that termination.
@vikramraman
=> MONIT-20606 - report missed termination statuses

.travis.yml, internal/metrics/metrics.go, plugins/sources/summary/summary.go
=> Add millicore metric from k8s reporting

plugins/manager/manager.go, plugins/manager/manager_test.go
MONIT-21247: pod and container counts (on cluster & ns) are incorrect when running in deployment mode.
=> fix pod & container counts

cmd/wavefront-collector/main.go, internal/configuration/config.go, plugins/manager/manager.go, plugins/manager/manager_test.go, plugins/sinks/wavefront/sink_test.go, plugins/sinks/wavefront/testsender.go, plugins/sinks/wavefront/wavefront.go
Add options to run collector once and output to log
MONIT-21520
Signed-off-by: Mark Michael <mamicheal@vmware.com>
=> Create mode to run collection once and output to json log

Makefile, deploy/examples/runtime/memcached-runtime-secret-config.yaml, deploy/kubernetes/1-collector-cluster-role.yaml, docs/discovery.md, hack/kustomize/base/1-collector-cluster-role.yaml, plugins/discovery/config.go, plugins/discovery/config_test.go
Fixes https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes/issues/83
=> Adds support for reading discovery rules from secrets

plugins/discovery/config_test.go
Signed-off-by: Joe Gee <jgee@vmware.com>
=> Formatting fix

cmd/wavefront-collector/main.go, hack/deploy/prom-example.yaml, hack/kustomize/base/4-collector-config.yaml, hack/kustomize/deploy.sh, hack/kustomize/overlays/test/collector.yaml.template, hack/kustomize/overlays/test/overrides.yml, hack/kustomize/test.sh, internal/configuration/config.go, plugins/sources/prometheus/prometheus.go
Plus a little test automation cleanup
=> Remove bulk processing algorithm for prometheus parser

plugins/sinks/wavefront/wavefront.go
=> Add comment with gc learnings

hack/deploy/memcached-config.yaml
Adds coverage to our secret discovery
=> Add secret config coverage to test loop

Makefile, deploy/kubernetes/5-collector-daemonset.yaml, deploy/openshift/collector/3-collector-deployment.yaml, hack/kustomize/base/5-collector-daemonset.yaml, hack/kustomize/deploy.sh, release/bump-version.sh
Signed-off-by: John Frederick Cornish IV <jcornish@pivotal.io>
=> Bump version to 1.3.5

adr/20210422-scrape-rest-periods.md
Signed-off-by: Jacob Schuenke <jschuenke@pivotal.io>
=> Add ADR for scrape rest period decision

Dockerfile.test-proxy, Makefile, hack/deploy/Dockerfile.test-proxy
Update test-proxy to use multi-stage docker build
=> Test proxy build caching

Makefile
TMC integrations need the higher resources
=> Add bigger machine type

deploy/kubernetes/4-collector-config.yaml, docs/configuration.md, hack/kustomize/base/4-collector-config.yaml
Signed-off-by: John Frederick Cornish IV <jcornish@pivotal.io>
=> Set annotation prefix back to prometheus.io except for tests.

Makefile
=> Update version for release

Makefile, hack/kustomize/test.sh, hack/make/push-container.sh, hack/make/script-tools.sh
...and also consolidate container pushing into script
=> Add eks test support

hack/deploy/deploy-targets.sh
=> delete jobs before every deploy-targets.sh

hack/kustomize/generate.sh, make/k8s-envs/shared.mk
- Also create make command for listing nodes with arch
=> Make wf cluster name more specific

plugins/processors/node_autoscaling_enricher.go, plugins/sinks/wavefront/wavefront.go
Signed-off-by: Matthew Conger-Eldeen <matthewco@vmware.com>
=> use working set instead of usage to calculate node memory utilization

Makefile, deploy/docker/Dockerfile-rhel, hack/test/deploy/deploy-local-alpha.sh, hack/test/deploy/deploy-local.sh
Signed-off-by: John Cornish <jcornish@vmware.com>
=> Make integration test work for RHEL collector image

deploy/kubernetes/6-wavefront-proxy.yaml, deploy/openshift/1-wavefront-proxy.yaml, deploy/tkgi/5-proxy-deployment.yaml, hack/test/base/proxy.template.yaml
Signed-off-by: Helen Shao <shaoh@vmware.com>
(cherry picked from commit 6872f6b1b0b66c169ac7e3ad1412bca28df1ce00)
=> Bump proxy version to 10.13

hack/test/test-e2e.sh
=> remove trailing zero

hack/test/base/collector.template.yaml, hack/test/dashboards/prototype-apiserver-details.json
Signed-off-by: Anil Kodali <akodali@vmware.com>
=> Add apiserver metrics, save prototype dashboard

deploy/examples/6-wavefront-proxy-with-http-proxy.yaml
Signed-off-by: Helen Shao <shaoh@vmware.com>
=> Add example to support proxy ca certs

deploy/examples/6-wavefront-proxy-with-http-proxy.yaml, deploy/kubernetes/6-wavefront-proxy.yaml, deploy/openshift/1-wavefront-proxy.yaml, deploy/tkgi/5-proxy-deployment.yaml, hack/test/base/proxy.template.yaml, hack/test/dashboards/deploy/6-wavefront-proxy.yaml
Signed-off-by: Priya Selvaganesan <pselvaganesa@vmware.com>
=> Update proxy version to 10.14

Makefile
Signed-off-by: Helen Shao <shaoh@vmware.com>
=> Remove docker login from make publish

.editorconfig
Yes permanentize is a real word leave me alone
https://www.google.com/search?q=permanentize&rlz=1C5CHFA_enUS962US964&oq=permanentize&aqs=chrome.0.69i59j0i30l5j69i60l2.575j1j9&sourceid=chrome&ie=UTF-8
=> Codify team config for YAML spacing!!!!

release.Jenkinsfile
=> remove clean up ws as it fails the slack notifications.

hack/test/clean-deploy.sh, hack/test/deploy.sh, hack/test/generate.sh
To use the format <username>-<env>-<YYMMDD>
=> Updates WF cluster name used in deploy-test and integraton-test

deploy/kubernetes/4-collector-config.yaml, hack/test/base/collector.template.yaml, hack/test/files/metrics.jsonl, hack/test/overlays/test-eks/metrics/additional.jsonl, hack/test/overlays/test-kind/metrics/additional.jsonl
Signed-off-by: John Cornish <jcornish@vmware.com>
=> Add control-plane-alert tag

deploy/kubernetes/4-collector-config.yaml, hack/test/base/collector.template.yaml, hack/test/files/metrics.jsonl, hack/test/overlays/test-eks/metrics/additional.jsonl, hack/test/overlays/test-kind/metrics/additional.jsonl
Reverts wavefrontHQ/wavefront-collector-for-kubernetes#414
=> Revert "Add control-plane-alert tag"

ci.Jenkinsfile
Signed-off-by: Helen Shao <shaoh@vmware.com>
=> Add EKS to jenkins pipeline

hack/jenkins/create-and-merge-pull-request.sh
Signed-off-by: Priya Selvaganesa <pselvaganesa@vmware.com>
=> Change base branch from master to main for release pipeline

open_source_licenses.txt
Co-authored-by: Helen Shao <shaoh@vmware.com>
=> Update version in license file

release.Jenkinsfile
Co-authored-by: Helen Shao <shaoh@vmware.com>
=> Update the required variable value in release pipeline

hack/test/deploy/deploy-local-linux.sh, release.Jenkinsfile
Co-authored-by: Helen Shao <shaoh@vmware.com>
=> Update deploy script for release

deploy/docker/Dockerfile-rhel
Signed-off-by: Matthew Conger-Eldeen <matthewco@vmware.com>
=> Upgrade openshift go version to 1.17

go.mod, go.sum, vendor/golang.org/x/net/AUTHORS, vendor/golang.org/x/net/CONTRIBUTORS, vendor/golang.org/x/net/context/context.go, vendor/golang.org/x/net/context/go17.go, vendor/golang.org/x/net/context/pre_go17.go, vendor/golang.org/x/net/http/httpguts/httplex.go, vendor/golang.org/x/net/http2/client_conn_pool.go, vendor/golang.org/x/net/http2/errors.go, vendor/golang.org/x/net/http2/frame.go, vendor/golang.org/x/net/http2/hpack/encode.go, vendor/golang.org/x/net/http2/hpack/hpack.go, vendor/golang.org/x/net/http2/hpack/huffman.go, vendor/golang.org/x/net/http2/http2.go, vendor/golang.org/x/net/http2/server.go, vendor/golang.org/x/net/http2/transport.go, vendor/golang.org/x/net/http2/writesched_priority.go, vendor/golang.org/x/net/idna/trieval.go, vendor/modules.txt
Co-authored-by: Mark Michael <mamichael@vmware.com>
=> Upgrade net to fix CVE-2022-27664

Makefile
Make sure to branch out from main to ensure correct git history while creating PR's.
=> Make sure to branch out from main to ensure correct git history while merging

hack/code-health-and-support/get-troubleshooting-info.sh
Signed-off-by: Ginwoo Pak <pginwoo@vmware.com>
=> update get-troubleshooting-info.sh for operator

hack/jenkins/setup-for-integration-test.sh
Co-authored-by: Mark Michael <mamichael@vmware.com>
=> Fix GKE setup to install gke-gcloud-auth-plugin
